import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fdf8f6",
        primary: "#983912",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fdf8f6",
        surface: "#fdf8f6",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#32302f",
        "secondary-fixed": "#d3e7db",
        "primary-fixed": "#ffdbcf",
        "surface-container-low": "#f7f3f0",
        "on-secondary-container": "#54675d",
        "tertiary-fixed": "#bce9ff",
        outline: "#8a726a",
        tertiary: "#005f79",
        "on-secondary-fixed-variant": "#384b41",
        secondary: "#506358",
        "primary-container": "#b85028",
        "on-surface-variant": "#57423b",
        error: "#ba1a1a",
        "on-tertiary-container": "#e8f6ff",
        "surface-container-highest": "#e6e2df",
        "on-tertiary": "#ffffff",
        "surface-tint": "#a13f18",
        "on-tertiary-fixed-variant": "#004d63",
        "secondary-fixed-dim": "#b7cbbf",
        "surface-container-high": "#ece7e5",
        "inverse-primary": "#ffb59c",
        "on-primary": "#ffffff",
        "surface-variant": "#e6e2df",
        "on-primary-fixed": "#380c00",
        "on-primary-container": "#fff2ee",
        "primary-fixed-dim": "#ffb59c",
        "on-surface": "#1c1b1a",
        "secondary-container": "#d0e5d8",
        "on-secondary-fixed": "#0d1f17",
        "on-primary-fixed-variant": "#812901",
        "outline-variant": "#ddc0b7",
        "surface-container": "#f2edeb",
        "on-tertiary-fixed": "#001f2a",
        "on-background": "#1c1b1a",
        "surface-dim": "#ddd9d7",
        "tertiary-fixed-dim": "#7bd1f6",
        "inverse-on-surface": "#f5f0ee",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "tertiary-container": "#00799a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xl": "3rem",
        "space-xs": "0.25rem",
        "space-lg": "1.75rem",
        "margin-desktop": "4rem",
        margin: "1.25rem",
        "space-md": "1rem",
        "gutter-desktop": "2.5rem",
        gutter: "1.5rem",
        "space-2xl": "5rem",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "headline-xl": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "body-md": ["Inter", "sans-serif"],
        subhead: ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["1rem", { lineHeight: "1.625rem", fontWeight: "400" }],
        "headline-xl-mobile": [
          "2.25rem",
          { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "headline-lg": [
          "2.25rem",
          { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "label-caps": [
          "0.6875rem",
          { lineHeight: "1rem", letterSpacing: "0.08em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "1.75rem",
          { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "headline-xl": [
          "3.5rem",
          { lineHeight: "4rem", letterSpacing: "-0.03em", fontWeight: "400" },
        ],
        "headline-md": [
          "1.5rem",
          { lineHeight: "2rem", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "body-md": ["0.875rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        subhead: [
          "1.125rem",
          { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "label-code": [
          "0.8125rem",
          { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;